import tkinter as tk
def saludar():
    nombre = entrada_saludar.get()
    etiqueta_resultado_saludar.config(text=f"Hola {nombre}")
def edades():
    edad = entrada_edad.get()
    etiqueta_resultado_edad.config(text=f"tienes {edad} años")
ventana = tk.Tk()
ventana.title("mi primera app grafica")
ventana.geometry("400x250")
ventana.configure(background='light blue')
etiqueta_saludar = tk.Label(ventana, text="Ingresa tu nombre:")
etiqueta_saludar.pack()
etiqueta_saludar.configure(background='light blue')
entrada_saludar = tk.Entry(ventana)
entrada_saludar.pack()
entrada_saludar.configure(background='light gray')
boton_saludar = tk.Button(ventana, text="Saludar", command=saludar)
boton_saludar.pack()
etiqueta_resultado_saludar = tk.Label(ventana, text="")
etiqueta_resultado_saludar.pack()
etiqueta_resultado_saludar.configure(background='light blue')
etiqueta_edad = tk.Label(ventana, text="ingresa tu edad:")
etiqueta_edad.pack()
etiqueta_edad.configure(background='light blue')
entrada_edad = tk.Entry(ventana)
entrada_edad.pack()
entrada_edad.configure(background='light gray')
boton_edad = tk.Button(ventana, text="Mostrar edad", command=edades)
boton_edad.pack()
etiqueta_resultado_edad = tk.Label(ventana, text="")
etiqueta_resultado_edad.pack()
etiqueta_resultado_edad.configure(background='light blue')
etiqueta = tk.Label(ventana, text="Valentina Jiménez Francisco")
etiqueta.pack()
etiqueta.configure(background='light gray')
ventana.mainloop()
