import tkinter as tk
def saludar():
    nombre = entrada_saludo.get()
    etiqueta_resultado_saludo.config(text=f"Hola {nombre}")
def edad():
   edad = entrada_edad.get()
   etiqueta_resultado_edad.config(text=f"Tienes {edad} años")
ventana = tk.Tk()
ventana.title("Mi primera app grafica")
ventana.geometry("400x200")
etiqueta_saludo = tk.Label(ventana, text="Ingresa tu nombre: ")
etiqueta_saludo.pack()
entrada_saludo = tk.Entry(ventana)
entrada_saludo.pack()
boton_saludo = tk.Button(ventana, text="Saludar", command=saludar)
boton_saludo.pack()
etiqueta_resultado_saludo = tk.Label(ventana, text="")
etiqueta_resultado_saludo.pack()
etiqueta_edad = tk.Label(ventana, text="ingresa tu edad: ")
etiqueta_edad.pack()
entrada_edad = tk.Entry(ventana)
entrada_edad.pack()
boton_edad = tk.Button(ventana, text="Mostrar edad", command=edd)
boton_edad.pack()
etiqueta_resultado_edad = tk.Label(ventana, text="")
etiqueta_resultado_edad.pack()
ventana.mainloop()
